### ISSUE TITLE
'NullPointerException' thrown from 'handleWakeLockRelease'.

### ISSUE THREAD

**Issue by nyanyani** [Jasper-1024/NoWakeLock#13]
Android version: MIUI 12.5.17
Magisk version name: 25.1
Magisk version code: 25100

Log here:
```
[ 2022-11-08T13:33:16.565     1000:  1419:  6547 E/LSPosed-Bridge  ] java.lang.NullPointerException
	at com.js.nowakelock.xposedhook.hook.WakelockHook$Companion.handleWakeLockRelease(WakelockHook.kt:265)
	at com.js.nowakelock.xposedhook.hook.WakelockHook$Companion.access$handleWakeLockRelease(WakelockHook.kt:20)
	at com.js.nowakelock.xposedhook.hook.WakelockHook$Companion$wakeLockHook24to30$2.beforeHookedMethod(WakelockHook.kt:228)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.releaseWakeLockInternal(Unknown Source:18)
	at com.android.server.power.PowerManagerService.access$4700(PowerManagerService.java:127)
	at com.android.server.power.PowerManagerService$BinderService.releaseWakeLock(PowerManagerService.java:4960)
	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:449)
	at com.android.server.power.MiuiPowerManagerServiceStub.onTransact(MiuiPowerManagerServiceStub.java:491)
	at android.os.Binder.execTransactInternal(Binder.java:1157)
	at android.os.Binder.execTransact(Binder.java:1126)
```

https://github.com/Jasper-1024/NoWakeLock/blob/ad8458710c71840e59cb677691e0bc85dd6160b0/app/src/main/java/com/js/nowakelock/xposedhook/hook/WakelockHook.kt#L265

**Comment by nyanyani** [comment]
never mind, i just modified this fun to return if `wlT` is null.
```kt
val wlT: WLT? = wlTs[lock]
if(null == wlT) {
    return
}
```

**Comment by Jasper-1024** [comment]
There is someone meet the same error, for now i just use the same bug.
Current practice
- It seems that this error does not affect the normal use of the application.
- Now just add the null judgment to mask the error output.

**Comment by Jasper-1024** [comment]
There is someone meet the same error, for now i just use the same bug.
Current practice

    It seems that this error does not affect the normal use of the application.
    Now just add the null judgment to mask the error output.
