### ISSUE TITLE
[BUG] Doesn't work on Android 14

### ISSUE THREAD

**Issue by HarriBuh** [Jasper-1024/NoWakeLock#17]
I don't understand why Instagram is involved in this issue, though...

[Device Brand]: google
[Device Model]: Pixel 7
[Android Version]: 14
[Android API Level]: 34
[Process ID]: 5792
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.js.nowakelock
[Version Name]: 2.0.0-beta3
[Version Code]: 55
[Target SDK]: 33
[Min SDK]: 24
[Error Type]: JVM
[Crash Time]: 2024-02-23T00:00:58.648
[Stack Trace]:
java.lang.IllegalArgumentException: Unknown package: com.instagram.lite
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.content.pm.IPackageManager$Stub$Proxy.getApplicationEnabledSetting(IPackageManager.java:6125)
	at android.app.ApplicationPackageManager.getApplicationEnabledSetting(ApplicationPackageManager.java:3117)
	at com.js.nowakelock.data.repository.appdas.AppDasAR.getSysAppInfo(AppDasAR.kt:138)
	at com.js.nowakelock.data.repository.appdas.AppDasAR.access$getSysAppInfo(AppDasAR.kt:28)
	at com.js.nowakelock.data.repository.appdas.AppDasAR$getSysAppInfos$2.invokeSuspend(AppDasAR.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1afebc4, Dispatchers.Main.immediate]

**Comment by Jasper-1024** [comment]
Ok, after receiving the feedback, I will flash the device I have to Android 14 in the near future to reproduce the problem.

According to the log content, the problem is caused by changes in the system API and has nothing to do with Instagram. It may just happen that Instagram applies for a wake lock, and then accesses the changed system API when recording nowakelock.

**Comment by HarriBuh** [comment]
Any news on this issue? It's already June

**Comment by Jasper-1024** [comment]
yes...😢😢😢
